### ISSUE TITLE
FunctionClauseError in GoogleCloudLogger formatter

### ISSUE THREAD

**Issue by alco** [Nebo15/logger_json#17]
```
:gen_event handler LoggerJSON installed in Logger terminating
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in LoggerJSON.Formatters.GoogleCloudLogger.format_crash_reason/1
        (logger_json) lib/logger_json/formatters/google_cloud_logger.ex:75: LoggerJSON.Formatters.GoogleCloudLogger.format_crash_reason({{:bad_label, {:alabel, 'The label "docker_host"  is not a valid A-label: ulabel error={bad_label,\n                                                               {context,\n                                                                "Codepoint 95 not allowed (\'DISALLOWED\') at posion 6 in \\"docker_host\\""}}'}}, [{:idna, :alabel, 1, [file: '/opt/app/deps/idna/src/idna.erl', line: 277]}, {:idna, :encode_1, 2, [file: '/opt/app/deps/idna/src/idna.erl', line: 145]}, {:hackney_url, :normalize, 2, [file: '/opt/app/deps/hackney/src/hackney_url.erl', line: 99]}, {:hackney, :request, 5, [file: '/opt/app/deps/hackney/src/hackney.erl', line: 305]}, {DealershipsCatalog.HTTPClient, :fetch_file, 2, [file: 'lib/dealerships_catalog/http_client.ex', line: 11]}, {DealershipsCatalog.ProductFeeds, :do_check_for_updates, 2, [file: 'lib/dealerships_catalog/product_feeds.ex', line: 120]}, {DealershipsCatalog.Util, :with_tmp_path, 2, [file: 'lib/dealerships_catalog/util.ex', line: 12]}, {Task.Supervised, :do_apply, 2, [file: 'lib/task/supervised.ex', line: 89]}]})
        (logger_json) lib/logger_json/formatters/google_cloud_logger.ex:67: anonymous fn/3 in LoggerJSON.Formatters.GoogleCloudLogger.format_process_crash/1
        (jason) lib/encode.ex:163: Jason.Encode.map_naive/3
        (jason) lib/encode.ex:35: Jason.Encode.encode/2
        (jason) lib/jason.ex:197: Jason.encode_to_iodata!/2
        (logger_json) lib/logger_json.ex:299: LoggerJSON.format_event/5
        (logger_json) lib/logger_json.ex:234: LoggerJSON.log_event/5
        (logger_json) lib/logger_json.ex:139: LoggerJSON.handle_event/2
```

It happens when I try to fetch a URL like `http://docker_host:9000/...` using hackney.

**Comment by mdaz78** [comment]
I am also getting the same issue, @alco How did you resolve it?

**Comment by alco** [comment]
@mdaz78 This was fixed in https://github.com/Nebo15/logger_json/commit/0f908157c4f7999e2c07e97b47d099f44c8317e0. @AndrewDryga Did that commit make it into release v3.0.2?

**Comment by AndrewDryga** [comment]
@alco yes, v3.0.2 is released.
